INSERT INTO category(id, name, description, version) VALUES (1000, 'Fish', 'Any of numerous cold-blooded aquatic vertebrates characteristically having fins, gills, and a streamlined body', 1)
INSERT INTO category(id, name, description, version) VALUES (1001, 'Dogs', 'A domesticated carnivorous mammal related to the foxes and wolves and raised in a wide variety of breeds', 1)
INSERT INTO category(id, name, description, version) VALUES (1002, 'Reptiles', 'Any of various cold-blooded, usually egg-laying vertebrates, such as a snake, lizard, crocodile, turtle', 1)
INSERT INTO category(id, name, description, version) VALUES (1003, 'Cats', ' Small carnivorous mammal domesticated since early times as a catcher of rats and mice and as a pet and existing in several distinctive breeds and varieties', 1)
INSERT INTO category(id, name, description, version) VALUES (1004, 'Birds', 'Any of the class Aves of warm-blooded, egg-laying, feathered vertebrates with forelimbs modified to form wings', 1)


INSERT INTO product(id, name, description, categoryId, version) VALUES (1000, 'Angelfish', 'Saltwater fish from Australia', 1000, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1001, 'Tiger Shark', 'Saltwater fish from Australia', 1000, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1002, 'Koi', 'Freshwater fish from Japan', 1000, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1003, 'Goldfish', 'Freshwater fish from China', 1000, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1004, 'Bulldog', 'Friendly dog from England', 1001, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1005, 'Poodle', 'Cute dog from France', 1001, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1006, 'Dalmation', 'Great dog for a fire station', 1001, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1007, 'Golden Retriever', 'Great family dog', 1001, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1008, 'Labrador Retriever', 'Great hunting dog', 1001, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1009, 'Chihuahua', 'Great companion dog', 1001, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1010, 'Rattlesnake', 'Doubles as a watch dog', 1002, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1011, 'Iguana', 'Friendly green friend', 1002, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1012, 'Manx', 'Great for reducing mouse populations', 1003, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1013, 'Persian', 'Friendly house cat, doubles as a princess', 1003, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1014, 'Amazon Parrot', 'Great companion for up to 75 years', 1004, 1)
INSERT INTO product(id, name, description, categoryId, version) VALUES (1015, 'Finch', 'Great stress reliever', 1004, 1)
